# Generated by Django 4.1.6 on 2026-03-26 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('total_hours_taken', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_Id', models.CharField(max_length=200)),
                ('First_name', models.CharField(max_length=200)),
                ('Designation', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Mobile_Number', models.CharField(max_length=200)),
                ('Registration_date', models.DateField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Gender', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=1000)),
                ('Location', models.CharField(max_length=1000)),
                ('User_role', models.CharField(max_length=200)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual_leaves', models.IntegerField(default=12)),
                ('sick_leaves', models.IntegerField(default=6)),
                ('compensatory_leaves', models.IntegerField(default=0)),
                ('additional_working_days', models.IntegerField(default=0)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Casual', 'Casual'), ('Sick', 'Sick'), ('Compensatory', 'Compensatory')], max_length=20)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('total_days', models.IntegerField()),
                ('reason', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='leave_documents/')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraWorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.FloatField(default=8.0)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreateProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_no', models.CharField(max_length=100, unique=True)),
                ('remarks', models.CharField(max_length=100)),
                ('week_no', models.CharField(blank=True, max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex_app.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Create_Timesheet_Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_no', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('total_hours_taken', models.IntegerField(default=0)),
                ('duration_hours', models.IntegerField(default=0)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('staff_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_lines', to='codex_app.registration')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_lines', to='codex_app.create_timesheet')),
            ],
        ),
        migrations.AddField(
            model_name='create_timesheet',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='codex_app.createproject'),
        ),
        migrations.AddField(
            model_name='create_timesheet',
            name='staff_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex_app.registration'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave')], default='Present', max_length=50)),
                ('total_working_days', models.PositiveIntegerField(default=0)),
                ('total_working_hours', models.FloatField(default=0.0)),
                ('webcam_image_in', models.ImageField(blank=True, null=True, upload_to='attendance_images/')),
                ('webcam_image_out', models.ImageField(blank=True, null=True, upload_to='attendance_images/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='codex_app.registration')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalWorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.TextField()),
                ('submitted_at', models.DateField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
