# Generated by Django 6.0.5 on 2026-05-18 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex_app', '0003_client_expensecategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('da', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('travel_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pf_percentage', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('esi_percentage', models.DecimalField(decimal_places=2, default=0.75, max_digits=5)),
                ('overtime_rate_per_hour', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='codex_app.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_working_days', models.IntegerField(default=0)),
                ('present_days', models.IntegerField(default=0)),
                ('leave_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('overtime_hours', models.FloatField(default=0)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leave_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pf_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('esi_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('incentive', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex_app.registration')),
            ],
            options={
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
