# Generated by Django 6.0.5 on 2026-07-15 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex_app', '0010_remove_create_timesheet_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='codex_app.createproject'),
        ),
    ]
