# Generated by Django 6.0.5 on 2026-07-15 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex_app', '0011_alter_projectmember_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex_app.createproject'),
        ),
        migrations.AlterField(
            model_name='income',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='codex_app.createproject'),
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex_app.createproject'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='codex_app.createproject'),
        ),
        migrations.AlterField(
            model_name='projectincome',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex_app.createproject'),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='codex_app.createproject'),
        ),
    ]
